services:
  postgresdb:
    image: postgres
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend: 
    build: ./backend/.
    ports: 
      - 3333:3333
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=task_manager
    command: npm start
    depends_on:
      postgresdb:
        condition: service_healthy
  frontend:
    build: ./frontend/.
    ports:
      - 5173:5173
    command: npm run dev
    depends_on:
      - backend
    environment:
      - VITE_HOSTNAME_BACKEND=http://localhost:3333/